name: fire_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.7.0
  firebase_core: 1.21.1
  firebase_storage: 10.3.7
  modal_progress_hud_nsn: ^0.3.0
  google_sign_in: 5.4.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.8
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appIcon.png"

flutter: 
  uses-material-design: true
  assets:
    - images/

